import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const css = readFileSync(new URL("../app/graph.css", import.meta.url), "utf8");
const page = readFileSync(new URL("../app/page.tsx", import.meta.url), "utf8");

test("unavailable AI remains visible and the optional sample cannot request inference", () => {
  const start = page.indexOf('{selectedSymbol && !canInterpretSelected');
  const panel = page.slice(start, page.indexOf('{canInterpretSelected &&', start));
  assert.ok(start >= 0);
  assert.match(panel, /AI generation is disabled for imported JSON reports/);
  assert.match(panel, /does not restore a previous AI explanation/);
  assert.match(panel, /Handwritten UI sample · not model output/);
  assert.match(panel, /not an explanation of the selected symbol/);
  assert.doesNotMatch(panel, /onClick|fetch\(|interpretSelectedSymbol/);
  assert.match(page, /if \(!selectedSymbol\?\.evidence_packet \|\| importedReport\) return/);
});

test("execution facts precede optional AI and preserve trust and source navigation", () => {
  const facts = page.indexOf('className="local-execution-section"');
  const ai = page.indexOf('className="ai-interpretation-section"');
  assert.ok(facts >= 0 && facts < ai);
  const panel = page.slice(facts, page.indexOf('{explanation &&', facts));
  assert.match(panel, /Imported · unverified/);
  assert.match(panel, /No local execution facts were recorded/);
  assert.match(panel, /not generated by AI or observed at runtime/);
  assert.match(panel, /href="#selected-source"/);
  assert.match(page, /id="selected-source" tabIndex=\{-1\}/);
  assert.match(page, /!executionFacts.includes\(claim\)/);
  assert.match(page, /AI can contradict the evidence even when citations are valid/);
});

test("desktop workspace bounds both sidebars instead of only the inspector", () => {
  const desktop = css.slice(css.indexOf("@media (min-width: 1001px)"), css.indexOf("/* Stacked sidebars"));
  assert.match(desktop, /\.shell\s*\{[^}]*height: 100dvh/);
  assert.match(desktop, /\.workspace\s*\{[^}]*min-height: 0[^}]*grid-template-rows: minmax\(0, 1fr\)/);
  assert.match(desktop, /\.rail, \.detail\s*\{[^}]*height: 100%[^}]*overflow-y: auto[^}]*overscroll-behavior-y: contain/);
  assert.match(desktop, /\.graph-surface\s*\{[^}]*height: auto/);
  assert.match(page, /className="rail" aria-label="Repository controls" tabIndex=\{0\}/);
  assert.match(page, /className="detail" aria-label="Selected code details" aria-live="polite" tabIndex=\{0\}/);
});

test("stacked sidebars use document scrolling on mobile and tablet", () => {
  assert.match(css, /@media \(max-width: 1000px\)\s*\{\s*\.rail, \.detail\s*\{ height: auto; max-height: none; overflow: visible;/);
});

test("prominent example notice is tied to loaded report origin, not a repository name", () => {
  assert.match(page, /graph && reportOrigin === "example" && <section className="example-report-banner"/);
  assert.match(page, /Example report · Cosmic Python/);
  assert.match(page, /not a repository you submitted/);
  assert.match(page, /choose Analyze repository to create your own map/);
});

test("hosted AI uses only the runtime report reference and selected node", () => {
  assert.match(page, /useHostedInterpretation \? "\/api\/interpret\/deep"/);
  assert.match(page, /\? \{ reportId: evidenceReference\.reportId, nodeId: selectedSymbol\.id \}/);
  assert.match(page, /setEvidenceReference\(trustedEvidence\)/);
  assert.doesNotMatch(page, /serializeReport\([^)]*evidenceReference/);
  assert.match(page, /data\.commitSha !== graph\?\.snapshot\?\.commit_sha \|\| data\.nodeId !== selectedSymbol\.id/);
});
